# Generated by Django 5.2 on 2025-12-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0062_customer_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderhistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
